export const userSelect = {
  id: true,
  name: true,
  email: true,
  picture: true,
  phone: true,
  gender: true,
  website: true,
  stripeCustomerId: true,
  stripeAccountId: true,
  createdAt: true,
  fcmToken: true,
  isOnline: true,
  socialLogin: true,
  isGuest: true,
  address: true,
  locationType: true,
  latitude: true,
  longitude: true,
  auth: { select: { id: true, role: true, isVerified: true } },
} as const;
